# Generated by Django 5.1 on 2024-08-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amostra_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite o nomme da atividade. Ex. Extrair, Centrifugar, ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_empresa', models.PositiveIntegerField()),
                ('nome', models.CharField(blank=True, help_text='Digite o nome da nova empresa', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite o nomme do marcador ou trait. Estar informação será mult empresa e projeto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho_placa', models.CharField(choices=[('96', '96'), ('384', '384'), ('1536', '1536')], max_length=20)),
                ('placa_numero', models.PositiveIntegerField(default=0)),
                ('processada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite o nomme do Status. Exemplo: ativo / inativo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoResultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite o nomme do resultado. Ex. Positivo, Negativo, ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordenada_x', models.FloatField()),
                ('coordenada_y', models.FloatField()),
                ('id_amostra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.amostra')),
                ('id_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_projeto', models.PositiveIntegerField()),
                ('qt_amostras', models.PositiveIntegerField(blank=True, null=True)),
                ('amostras_geradas', models.BooleanField()),
                ('ativo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='placa',
            name='id_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projeto'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='id_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projeto'),
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processada', models.BooleanField(default=False)),
                ('id_marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marcador')),
                ('id_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.placa')),
                ('id_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiporesultado')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_placa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='app.placa')),
                ('id_placa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='app.placa')),
            ],
        ),
    ]
